//案例数据
var demoArr = [
	{title:'H5',author:'L',date:'2016.03.03',kt:'H5-响应式个人博客',src:'demo/blogs/blogs.png',href:"demo/blogs/index.html"},
	{title:'js',date:'2015.06.03',kt:'jq-选项卡',src:'demo/JS-JQ/jq- 选项卡/thumbnail.jpg',href:"demo/JS-JQ/jq- 选项卡/demo.html"},
	{title:'js',date:'2015.06.04',kt:'jq-百度换肤',src:'demo/JS-JQ/jq-QQ换肤/thumbnail.jpg',href:"demo/JS-JQ/jq-QQ换肤/demo.html"},
	{title:'js',date:'2015.06.06',kt:'jq-楼梯导航滚动',src:'demo/JS-JQ/jq-楼梯导航滚动/thumbnail.jpg',href:"demo/JS-JQ/jq-楼梯导航滚动//index.html"},
	{title:'js',date:'2015.06.10',kt:'jq-面向对象星星闪动',src:'demo/JS-JQ/jq-面向对象星星闪动/thumbnail.jpg',href:"demo/JS-JQ/jq-面向对象星星闪动/demo.html"},
	{title:'js',date:'2015.06.20',kt:'jq-腾迅课程 banner',src:'demo/JS-JQ/jq-腾迅课程 banner/thumbnail.jpg',href:"demo/JS-JQ/jq-腾迅课程 banner/index.html"},
	{title:'js',date:'2015.06.25',kt:'jq-无缝滚动',src:'demo/JS-JQ/jq-无缝滚动/thumbnail.jpg',href:"demo/JS-JQ/jq-无缝滚动/demo.html"},
	{title:'js',date:'2015.06.30',kt:'jq-淘宝banner',src:'demo/JS-JQ/jq-淘宝banner/thumbnail.jpg',href:"demo/JS-JQ/jq-淘宝banner/demo.html"},
	{title:'js',date:'2015.07.5',kt:'jq-小米官网全屏滚动',src:'demo/JS-JQ/jq-小米官网全屏滚动/thumbnail.jpg',href:"demo/JS-JQ/jq-小米官网全屏滚动/index.html"},
	{title:'js',date:'2015.07.10',kt:'jq-烟花特效',src:'demo/JS-JQ/jq-烟花特效/thumbnail.jpg',href:"demo/JS-JQ/jq-烟花特效/demo.html"},
	{title:'js',date:'2015.07.15',kt:'js-原生jsonp 跨域请求百度搜索功能',src:'demo/JS-JQ/js-原生jsonp 跨域请求百度搜索功能/thumbnail.jpg',href:"demo/JS-JQ/js-原生jsonp 跨域请求百度搜索功能/index.html"},
	{title:'js',date:'2015.07.20',kt:'原生js-banner1',src:'demo/JS-JQ/原生js-banner1/thumbnail.jpg',href:"demo/JS-JQ/原生js-banner1/demo.html"},
	{title:'js',date:'2015.07.25',kt:'原生js-banner2',src:'demo/JS-JQ/原生js-banner2/thumbnail.jpg',href:"demo/JS-JQ/原生js-banner2/demo.html"},
	{title:'js',date:'2015.07.30',kt:'原生js-banner3',src:'demo/JS-JQ/原生js-banner3/thumbnail.jpg',href:"demo/JS-JQ/原生js-banner3/index.html"},
	{title:'js',date:'2015.08.5',kt:'原生js-返回顶部特效',src:'demo/JS-JQ/原生js-返回顶部/thumbnail.jpg',href:"demo/JS-JQ/原生js-返回顶部/index.html"},
	{title:'js',date:'2015.08.10',kt:'原生js-飞机大战小游戏',src:'demo/JS-JQ/原生js-飞机大战游戏/thumbnail.jpg',href:"demo/JS-JQ/原生js-飞机大战游戏/index.html"},
	{title:'js',date:'2015.08.15',kt:'原生js后台登录验证',src:'demo/JS-JQ/原生js后台登录验证/thumbnail.jpg',href:"demo/JS-JQ/原生js后台登录验证/index.html"},
	{title:'js',date:'2015.08.20',kt:'原生js面向对象-猜拳小游戏',src:'demo/JS-JQ/原生js面向对象-猜拳游戏/thumbnail.jpg',href:"demo/JS-JQ/原生js面向对象-猜拳游戏/index.html"},
	{title:'js',date:'2015.06.25',kt:'原生js随机转换banner',src:'demo/JS-JQ/原生js随机转换banner/thumbnail.jpg',href:"demo/JS-JQ/原生js随机转换banner/banner.html"},
	{title:'js',date:'2015.06.25',kt:'原生js选项卡',src:'demo/JS-JQ/原生js选项卡/thumbnail.jpg',href:"demo/JS-JQ/原生js选项卡/demo.html"},
	{title:'js',date:'2015.06.26',kt:'jq-360全屏滚动',src:'demo/JS-JQ/jq-360全屏滚动/thumbnail.jpg',href:"demo/JS-JQ/jq-360全屏滚动/demo.html"},
	{title:'js',date:'2015.06.26',kt:'jq-QQ客服',src:'demo/JS-JQ/jq-QQ客服/thumbnail.jpg',href:"demo/JS-JQ/jq-QQ客服/QQ.html"},
	{title:'js',date:'2015.06.27',kt:'jq-QQ空间相册展示功能',src:'demo/JS-JQ/jq-QQ空间相册展示功能/thumbnail.jpg',href:"demo/JS-JQ/jq-QQ空间相册展示功能/demo.html"},
	{title:'js',date:'2015.06.27',kt:'jq-百度经验时光轴效果',src:'demo/JS-JQ/jq-百度经验时光轴效果/thumbnail.jpg',href:"demo/JS-JQ/jq-百度经验时光轴效果/demo.html"},
	{title:'js',date:'2015.06.28',kt:'jq-百度微任务',src:'demo/JS-JQ/jq-百度微任务/thumbnail.jpg',href:"demo/JS-JQ/jq-百度微任务/index.html"},
	{title:'js',date:'2015.06.29',kt:'jq-京东banner',src:'demo/JS-JQ/jq-京东banner/thumbnail.jpg',href:"demo/JS-JQ/jq-京东banner/demo.html"},
	{title:'js',date:'2015.06.30',kt:'jq-楼梯导航',src:'demo/JS-JQ/jq-楼梯导航/thumbnail.jpg',href:"demo/JS-JQ/jq-楼梯导航/demo.html"},
	{title:'js',date:'2015.07.02',kt:'jq-门户网站二级滑动菜单',src:'demo/JS-JQ/jq-门户网站二级滑动菜单/thumbnail.jpg',href:"demo/JS-JQ/jq-门户网站二级滑动菜单/Menu.html"},
	{title:'js',date:'2015.07.03',kt:'jq-全屏滚动',src:'demo/JS-JQ/jq-全屏滚动/thumbnail.jpg',href:"demo/JS-JQ/jq-全屏滚动/demo.html"},
	{title:'js',date:'2015.07.05',kt:'Jq-瑞丽网排行榜',src:'demo/JS-JQ/Jq-瑞丽网排行榜/thumbnail.jpg',href:"demo/JS-JQ/Jq-瑞丽网排行榜/demo.html"},
	{title:'js',date:'2015.07.06',kt:'jq-上传图片放大镜效果',src:'demo/JS-JQ/jq-上传图片放大镜效果/thumbnail.jpg',href:"demo/JS-JQ/jq-上传图片放大镜效果/demo.html"},
	{title:'js',date:'2015.07.07',kt:'jq-手风琴',src:'demo/JS-JQ/jq-手风琴/thumbnail.jpg',href:"demo/JS-JQ/jq-手风琴/demo.html"},
	{title:'js',date:'2015.07.09',kt:'jq-淘宝放大镜',src:'demo/JS-JQ/jq-淘宝放大镜/thumbnail.jpg',href:"demo/JS-JQ/jq-淘宝放大镜/demo.html"},
	{title:'js',date:'2015.07.10',kt:'jq-同程旅游选项卡',src:'demo/JS-JQ/jq-同程旅游选项卡/thumbnail.jpg',href:"demo/JS-JQ/jq-同程旅游选项卡/demo.html"},
	{title:'js',date:'2015.07.11',kt:'jq-图片沿时加载效果',src:'demo/JS-JQ/jq-图片沿时加载效果/thumbnail.jpg',href:"demo/JS-JQ/jq-图片沿时加载效果/demo.html"},
	{title:'js',date:'2015.07.13',kt:'jq-图片展示效果',src:'demo/JS-JQ/jq-图片展示效果/thumbnail.jpg',href:"demo/JS-JQ/jq-图片展示效果/demo.html"},
	{title:'js',date:'2015.07.14',kt:'jq-无缝滚动切换',src:'demo/JS-JQ/jq-无缝滚动切换/thumbnail.jpg',href:"demo/JS-JQ/jq-无缝滚动切换/demo.html"},
	{title:'js',date:'2015.07.16',kt:'jq-吸顶盒导航特效',src:'demo/JS-JQ/jq-吸顶盒导航特效/thumbnail.jpg',href:"demo/JS-JQ/jq-吸顶盒导航特效/demo.html"},
	{title:'js',date:'2015.07.17',kt:'jq-选项卡新闻动态切换效果',src:'demo/JS-JQ/jq-选项卡新闻动态切换效果/thumbnail.jpg',href:"demo/JS-JQ/jq-选项卡新闻动态切换效果/demo.html"},
	{title:'js',date:'2015.07.18',kt:'jq-折叠导航',src:'demo/JS-JQ/jq-折叠导航/thumbnail.jpg',href:"demo/JS-JQ/jq-折叠导航/demo.html"},
	{title:'js',date:'2015.07.19',kt:'jq-支付宝首页banner',src:'demo/JS-JQ/jq-支付宝首页banner/thumbnail.jpg',href:"demo/JS-JQ/jq-支付宝首页banner/demo.html"},
	{title:'js',date:'2015.07.22',kt:'jq-携程网2015',src:'demo/JS-JQ/jq-携程网2015/thumbnail.jpg',href:"demo/JS-JQ/jq-携程网2015/demo.html"},
	{title:'js',date:'2015.07.23',kt:'jq-途牛首页景点banner',src:'demo/JS-JQ/jq-途牛首页景点banner/thumbnail.jpg',href:"demo/JS-JQ/jq-途牛首页景点banner/demo.html"},
	{title:'js',date:'2015.07.25',kt:'jq-潭州全屏banner轮播',src:'demo/JS-JQ/jq-潭州全屏banner轮播/thumbnail.jpg',href:"demo/JS-JQ/jq-潭州全屏banner轮播/demo.html"},
	{title:'js',date:'2015.07.26',kt:'jq-产品切换展示',src:'demo/JS-JQ/jq-产品切换展示/thumbnail.jpg',href:"demo/JS-JQ/jq-产品切换展示/demo.html"},
	{title:'js',date:'2015.07.27',kt:'jq-图片描述展示',src:'demo/JS-JQ/jq-图片描述展示/thumbnail.jpg',href:"demo/JS-JQ/jq-图片描述展示/demo.html"},
	{title:'js',date:'2015.07.28',kt:'jq-水滴Tab',src:'demo/JS-JQ/jq-水滴Tab/thumbnail.jpg',href:"demo/JS-JQ/jq-水滴Tab/demo.html"},
	{title:'js',date:'2015.07.29',kt:'jq-全屏轮播banner',src:'demo/JS-JQ/jq-全屏轮播banner/thumbnail.jpg',href:"demo/JS-JQ/jq-全屏轮播banner/demo.html"},
	{title:'js',date:'2015.07.30',kt:'jq-鼠标划过慢慢展示Tab',src:'demo/JS-JQ/jq-鼠标划过慢慢展示Tab/thumbnail.jpg',href:"demo/JS-JQ/jq-鼠标划过慢慢展示Tab/demo.html"},
	{title:'js',date:'2015.08.10',kt:'jq-猫扑导航',src:'demo/JS-JQ/jq-猫扑导航/thumbnail.jpg',href:"demo/JS-JQ/jq-猫扑导航/demo.html"},
	{title:'js',date:'2015.08.20',kt:'jq-小米官网banner',src:'demo/JS-JQ/jq-小米官网banner/thumbnail.jpg',href:"demo/JS-JQ/jq-小米官网banner/demo.html"},
	{title:'js',date:'2015.08.25',kt:'jq-魅族导航',src:'demo/JS-JQ/jq-魅族导航/thumbnail.jpg',href:"demo/JS-JQ/jq-魅族导航/demo.html"},
	{title:'js',date:'2015.08.30',kt:'jq-魅族全屏banner',src:'demo/JS-JQ/jq-魅族全屏banner/thumbnail.jpg',href:"demo/JS-JQ/jq-魅族全屏banner/demo.html"},
	{title:'js',date:'2015.08.31',kt:'jq-魅族官网首页',src:'demo/JS-JQ/jq-魅族官网首页/thumbnail.jpg',href:"demo/JS-JQ/jq-魅族官网首页/demo.html"},
	{title:'js',date:'2015.09.10',kt:'jq-产品Tab展示',src:'demo/JS-JQ/jq-产品Tab展示/thumbnail.jpg',href:"demo/JS-JQ/jq-产品Tab展示/demo.html"},
	{title:'js',date:'2015.09.20',kt:'jq-潭州产品Tab',src:'demo/JS-JQ/jq-潭州产品Tab/thumbnail.jpg',href:"demo/JS-JQ/jq-潭州产品Tab/demo.html"},
	{title:'js',date:'2015.09.30',kt:'jq-酒仙网Tab',src:'demo/JS-JQ/jq-酒仙网Tab/thumbnail.jpg',href:"demo/JS-JQ/jq-酒仙网Tab/demo.html"},
	{title:'js',date:'2015.10.10',kt:'jq-鼠标划过显示内容',src:'demo/JS-JQ/jq-鼠标划过显示内容/thumbnail.jpg',href:"demo/JS-JQ/jq-鼠标划过显示内容/demo.html"},
	{title:'js',date:'2015.10.25',kt:'jq-京东产品展示',src:'demo/JS-JQ/jq-京东产品展示/thumbnail.jpg',href:"demo/JS-JQ/jq-京东产品展示/demo.html"},
	{title:'js',date:'2015.10.29',kt:'jq-瑞丽网产品展示',src:'demo/JS-JQ/jq-瑞丽网产品展示/thumbnail.jpg',href:"demo/JS-JQ/jq-瑞丽网产品展示/demo.html"},
	{title:'js',date:'2015.11.06',kt:'jq-芒果Tv banner',src:'demo/JS-JQ/jq-芒果Tv banner/thumbnail.jpg',href:"demo/JS-JQ/jq-芒果Tv banner/demo.html"},
	{title:'js',date:'2015.11.10',kt:'全民水浒界面',src:'demo/JS-JQ/全民水浒界面/thumbnail.jpg',href:"demo/JS-JQ/全民水浒界面/demo.html"},
	{title:'js',date:'2015.12.14',kt:'jq-潭州吸顶盒',src:'demo/JS-JQ/jq-潭州吸顶盒/thumbnail.jpg',href:"demo/JS-JQ/jq-潭州吸顶盒/demo.html"},
	{title:'js',date:'2015.12.16',kt:'潭州后台登录界面',src:'demo/JS-JQ/潭州后台登录界面/thumbnail.jpg',href:"demo/JS-JQ/潭州后台登录界面/demo.html"},
	{title:'js',date:'2016.01.11',kt:'jq-开门红',src:'demo/JS-JQ/jq-开门红/thumbnail.jpg',href:"demo/JS-JQ/jq-开门红/demo.html"},
	{title:'js',date:'2016.01.23',kt:'jq-潭州教育banner',src:'demo/JS-JQ/jq-潭州教育banner/thumbnail.jpg',href:"demo/JS-JQ/jq-潭州教育banner/demo.html"},
	{title:'js',date:'2016.01.25',kt:'jq-全屏banner',src:'demo/JS-JQ/jq-全屏banner/thumbnail.jpg',href:"demo/JS-JQ/jq-全屏banner/demo.html"},
	{title:'js',date:'2016.02.08',kt:'jq-百度导航',src:'demo/JS-JQ/jq-百度导航/thumbnail.jpg',href:"demo/JS-JQ/jq-百度导航/demo.html"},
	{title:'js',date:'2016.02.24',kt:'jq-换肤效果',src:'demo/JS-JQ/jq-换肤效果/thumbnail.jpg',href:"demo/JS-JQ/jq-换肤效果/demo.html"},
	{title:'js',date:'2016.02.27',kt:'jq-视频列表展示',src:'demo/JS-JQ/jq-视频列表展示/thumbnail.jpg',href:"demo/JS-JQ/jq-视频列表展示/demo.html"},
	{title:'js',date:'2016.03.16',kt:'jq-图片展示',src:'demo/JS-JQ/jq-图片展示/thumbnail.jpg',href:"demo/JS-JQ/jq-图片展示/demo.html"},
	{title:'js',date:'2016.04.12',kt:'jq-甘一客产品展示',src:'demo/JS-JQ/jq-甘一客产品展示/thumbnail.jpg',href:"demo/JS-JQ/jq-甘一客产品展示/demo.html"},
	
	{title:'HTML',date:'2015.09.03',kt:'1号店商城',src:'demo/HTML-DIV-CSS/1号店/thumbnail.jpg',href:"demo/HTML-DIV-CSS/1号店/index.html"},
	{title:'HTML',date:'2015.10.01',kt:'后台登录界面',src:'demo/HTML-DIV-CSS/后台登录界面/thumbnail.jpg',href:"demo/HTML-DIV-CSS/后台登录界面/index.html"},
	{title:'HTML',date:'2015.10.05',kt:'湖南海外旅游网站',src:'demo/HTML-DIV-CSS/湖南海外旅游网站/thumbnail.jpg',href:"demo/HTML-DIV-CSS/湖南海外旅游网站/index.html"},
	{title:'HTML',date:'2015.10.20',kt:'潭州学院官网',src:'demo/HTML-DIV-CSS/潭州学院官网/thumbnail.jpg',href:"demo/HTML-DIV-CSS/潭州学院官网/index.html"},
	{title:'HTML',date:'2015.11.02',kt:'企业平台',src:'demo/HTML-DIV-CSS/企业平台/thumbnail.jpg',href:"demo/HTML-DIV-CSS/企业平台//index.html"},
	{title:'HTML',date:'2015.11.30',kt:'小米官网',src:'demo/HTML-DIV-CSS/小米官网/thumbnail.jpg',href:"demo/HTML-DIV-CSS/小米官网/index.html"},
	{title:'HTML',date:'2015.12.10',kt:'中国神州旅游网站',src:'demo/HTML-DIV-CSS/中国神州旅游网站/thumbnail.jpg',href:"demo/HTML-DIV-CSS/中国神州旅游网站/index.html"},
	{title:'HTML',date:'2015.12.20',kt:'苹果中国Store官网效果',src:'demo/HTML-DIV-CSS/苹果中国Store官网效果/thumbnail.jpg',href:"demo/HTML-DIV-CSS/苹果中国Store官网效果/index.html"},
	{title:'HTML',date:'2016.01.01',kt:'瑞丽网',src:'demo/HTML-DIV-CSS/瑞丽网/thumbnail.jpg',href:"demo/HTML-DIV-CSS/瑞丽网/index.html"},
	{title:'HTML',date:'2016.02.01',kt:'潭州学院电商平台',src:'demo/HTML-DIV-CSS/潭州学院电商平台/thumbnail.jpg',href:"demo/HTML-DIV-CSS/潭州学院电商平台/index.html"},
	{title:'HTML',date:'2016.03.01',kt:'腾讯课堂',src:'demo/HTML-DIV-CSS/腾讯课堂/thumbnail.jpg',href:"demo/HTML-DIV-CSS/腾讯课堂/index.html"},
	{title:'HTML',date:'2016.03.01',kt:'魅族官网',src:'demo/HTML-DIV-CSS/魅族官网/thumbnail.jpg',href:"demo/HTML-DIV-CSS/魅族官网/index.html"},
	{title:'HTML',date:'2016.03.01',kt:'潭州后台登录界面',src:'demo/HTML-DIV-CSS/潭州后台登录界面/thumbnail.jpg',href:"demo/HTML-DIV-CSS/潭州后台登录界面/index.html"},

	{title:'CSs3',date:'2016.05.01',kt:'3D相册拖拽特效',src:'demo/HTML5-CSS3/3D相册拖拽特效/thumbnail.jpg',href:"demo/HTML5-CSS3/3D相册拖拽特效/demo.html"},
	{title:'H5',date:'2016.05.03',kt:'H5 cancas 绘制时钟',src:'demo/HTML5-CSS3/cancas 绘制时钟1/thumbnail.jpg',href:"demo/HTML5-CSS3/cancas 绘制时钟1/canvas.html"},
	{title:'H5',date:'2016.05.06',kt:'H5 cancas 绘制时钟',src:'demo/HTML5-CSS3/canvas 绘制时钟2/thumbnail.jpg',href:"demo/HTML5-CSS3/canvas 绘制时钟2/canvas.html"},
	{title:'CSs3',date:'2016.03.03',kt:'CSS3 3D盒子',src:'demo/HTML5-CSS3/CSS3 3D盒子/thumbnail.jpg',href:"demo/HTML5-CSS3/CSS3 3D盒子/demo.html"},
	{title:'CSs3',date:'2016.03.03',kt:'CSS3 3D球体',src:'demo/HTML5-CSS3/CSS3 3D球体/thumbnail.jpg',href:"demo/HTML5-CSS3/CSS3 3D球体/demo.html"},
	{title:'CSs3',date:'2016.03.03',kt:'CSS3 banner',src:'demo/HTML5-CSS3/CSS3 banner/thumbnail.jpg',href:"demo/HTML5-CSS3/CSS3 banner/demo.html"},
	{title:'CSs3',date:'2016.03.03',kt:'CSS3 风车',src:'demo/HTML5-CSS3/CSS3 风车/thumbnail.jpg',href:"demo/HTML5-CSS3/CSS3 风车/demo.html"},
	{title:'CSs3',date:'2016.03.03',kt:'css3 天猫左则导航',src:'demo/HTML5-CSS3/css3 天猫左则导航/thumbnail.jpg',href:"demo/HTML5-CSS3/css3 天猫左则导航/demo.html"},
	{title:'CSs3',date:'2016.03.03',kt:'css3 微信单页图标放大效果',src:'demo/HTML5-CSS3/css3 微信单页图标放大效果/thumbnail.jpg',href:"demo/HTML5-CSS3/css3 微信单页图标放大效果/demo.html"},
	{title:'CSs3',date:'2016.03.03',kt:'CSS3 无缝滚动',src:'demo/HTML5-CSS3/CSS3 无缝滚动/thumbnail.jpg',href:"demo/HTML5-CSS3/CSS3 无缝滚动/demo.html"},
	{title:'CSs3',date:'2016.03.03',kt:'CSS3 无缝滚动',src:'demo/HTML5-CSS3/CSS3 无缝滚动/index.png',href:"demo/HTML5-CSS3/CSS3 无缝滚动/index.html"},
	{title:'CSs3',date:'2016.03.03',kt:'CSS3 响应式导航',src:'demo/HTML5-CSS3/CSS3 响应式导航/thumbnail.jpg',href:"demo/HTML5-CSS3/CSS3 响应式导航/demo.html"},
	{title:'CSs3',date:'2016.03.03',kt:'CSS3 3D旋转',src:'demo/HTML5-CSS3/CSS3 3D旋转/thumbnail.png',href:"demo/HTML5-CSS3/CSS3 3D旋转/demo.html"},
	{title:'CSs3',date:'2016.03.03',kt:'CSS3 京东产品展示效果',src:'demo/HTML5-CSS3/CSS3 京东产品展示效果/thumbnail.jpg',href:"demo/HTML5-CSS3/CSS3 京东产品展示效果/demo.html"},
	{title:'CSs3',date:'2016.03.03',kt:'CSS3 鼠标划过放大效果',src:'demo/HTML5-CSS3/CSS3 鼠标划过放大效果/thumbnail.jpg',href:"demo/HTML5-CSS3/CSS3 鼠标划过放大效果/demo.html"},
	{title:'CSs3',date:'2016.03.03',kt:'CSS3 鼠标划过缩小',src:'demo/HTML5-CSS3/CSS3 鼠标划过缩小/thumbnail.jpg',href:"demo/HTML5-CSS3/CSS3 鼠标划过缩小/demo.html"},
	{title:'CSs3',date:'2016.03.03',kt:'CSS3 鼠标划过旋转',src:'demo/HTML5-CSS3/CSS3 鼠标划过旋转/thumbnail.jpg',href:"demo/HTML5-CSS3/CSS3 鼠标划过旋转/demo.html"},
	{title:'CSs3',date:'2016.03.03',kt:'CSS3 潭州产品展示',src:'demo/HTML5-CSS3/CSS3 潭州产品展示/thumbnail.jpg',href:"demo/HTML5-CSS3/CSS3 潭州产品展示/demo.html"},
	{title:'CSs3',date:'2016.03.03',kt:'CSS3 潭州电影播放列表',src:'demo/HTML5-CSS3/CSS3 潭州电影播放列表/thumbnail.jpg',href:"demo/HTML5-CSS3/CSS3 潭州电影播放列表/demo.html"},
	{title:'CSs3',date:'2016.03.03',kt:'CSS3 图片放大展示',src:'demo/HTML5-CSS3/CSS3 图片放大展示/thumbnail.jpg',href:"demo/HTML5-CSS3/CSS3 图片放大展示/demo.html"},
	{title:'CSs3',date:'2016.03.03',kt:'CSS3 小米4展示',src:'demo/HTML5-CSS3/CSS3 小米4展示/thumbnail.jpg',href:"demo/HTML5-CSS3/CSS3 小米4展示/demo.html"},
	{title:'CSs3',date:'2016.03.03',kt:'CSS3 音乐FM展示',src:'demo/HTML5-CSS3/CSS3 音乐FM展示/thumbnail.jpg',href:"demo/HTML5-CSS3/CSS3 音乐FM展示/demo.html"},
	{title:'CSs3',date:'2016.03.03',kt:'3D相册拖拽特效',src:'demo/HTML5-CSS3/3D相册拖拽特效/thumbnail.jpg',href:"demo/HTML5-CSS3/3D相册拖拽特效/demo.html"},
	{title:'H5',date:'2016.06.08',kt:'H5 原生js+H5视频播放器',src:'demo/HTML5-CSS3/H5 原生js+H5视频播放器/thumbnail.jpg',href:"demo/HTML5-CSS3/H5 原生js+H5视频播放器/demo.html"},
	{title:'H5',date:'2016.06.10',kt:'H5 原生js+H5音乐播放器',src:'demo/HTML5-CSS3/H5 原生js+H5音乐播放器/thumbnail.jpg',href:"demo/HTML5-CSS3/H5 原生js+H5音乐播放器/demo.html"},
	{title:'H5',author:'L',date:'2016.03.03',kt:'H5-响应式个人博客',src:'demo/blogs/blogs.png',href:"demo/blogs/index.html"},
	{title:'js',date:'2015.06.30',kt:'jq-淘宝banner',src:'demo/JS-JQ/jq-淘宝banner/thumbnail.jpg',href:"demo/JS-JQ/jq-淘宝banner/demo.html"},
	{title:'js',date:'2015.07.5',kt:'jq-小米官网全屏滚动',src:'demo/JS-JQ/jq-小米官网全屏滚动/thumbnail.jpg',href:"demo/JS-JQ/jq-小米官网全屏滚动/index.html"},
	{title:'js',date:'2015.07.10',kt:'jq-烟花特效',src:'demo/JS-JQ/jq-烟花特效/thumbnail.jpg',href:"demo/JS-JQ/jq-烟花特效/demo.html"},
	{title:'js',date:'2015.07.15',kt:'js-原生jsonp 跨域请求百度搜索功能',src:'demo/JS-JQ/js-原生jsonp 跨域请求百度搜索功能/thumbnail.jpg',href:"demo/JS-JQ/js-原生jsonp 跨域请求百度搜索功能/index.html"},
	{title:'js',date:'2015.07.20',kt:'原生js-banner1',src:'demo/JS-JQ/原生js-banner1/thumbnail.jpg',href:"demo/JS-JQ/原生js-banner1/demo.html"},
	{title:'js',date:'2015.07.25',kt:'原生js-banner2',src:'demo/JS-JQ/原生js-banner2/thumbnail.jpg',href:"demo/JS-JQ/原生js-banner2/demo.html"},
	{title:'js',date:'2015.07.30',kt:'原生js-banner3',src:'demo/JS-JQ/原生js-banner3/thumbnail.jpg',href:"demo/JS-JQ/原生js-banner3/index.html"},
	{title:'js',date:'2015.08.5',kt:'原生js-返回顶部特效',src:'demo/JS-JQ/原生js-返回顶部/thumbnail.jpg',href:"demo/JS-JQ/原生js-返回顶部/index.html"},
	{title:'js',date:'2015.08.10',kt:'原生js-飞机大战小游戏',src:'demo/JS-JQ/原生js-飞机大战游戏/thumbnail.jpg',href:"demo/JS-JQ/原生js-飞机大战游戏/index.html"},
	{title:'js',date:'2015.08.15',kt:'原生js后台登录验证',src:'demo/JS-JQ/原生js后台登录验证/thumbnail.jpg',href:"demo/JS-JQ/原生js后台登录验证/index.html"},
	{title:'js',date:'2015.08.20',kt:'原生js面向对象-猜拳小游戏',src:'demo/JS-JQ/原生js面向对象-猜拳游戏/thumbnail.jpg',href:"demo/JS-JQ/原生js面向对象-猜拳游戏/index.html"},
	{title:'js',date:'2015.06.25',kt:'原生js随机转换banner',src:'demo/JS-JQ/原生js随机转换banner/thumbnail.jpg',href:"demo/JS-JQ/原生js随机转换banner/banner.html"},
	{title:'HTML',date:'2015.09.03',kt:'1号店商城',src:'demo/HTML-DIV-CSS/1号店/thumbnail.jpg',href:"demo/HTML-DIV-CSS/1号店/index.html"},
		{title:'HTML',date:'2015.11.30',kt:'小米官网',src:'demo/HTML-DIV-CSS/小米官网/thumbnail.jpg',href:"demo/HTML-DIV-CSS/小米官网/index.html"},
];